### ISSUE TITLE
$ionicAuth.signup is not a function

### ISSUE THREAD

**Issue by user2301** [driftyco/creator-weekly-workshops#7]
I am new to ionic. I followed this setup for ionic cloud https://docs.ionic.io/setup.html. and in my register page I get this error  TypeError: $ionicAuth.signup is not a function. I am calling the function like this $ionicAuth.signup($scope.registerData).then(function() {...} But is says . $ionicAuth.signup is not a function.

**Comment by david-poindexter** [comment]
Working fine for us.
